apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: app1
            namespace: argocd
          - name: app2
            namespace: argocd
          - name: app3
            namespace: argocd
          - name: app4
            namespace: argocd
          - name: app5
            namespace: argocd
          - name: app6
            namespace: argocd
          - name: app7
            namespace: argocd
          - name: app8
            namespace: argocd
          - name: app9
            namespace: argocd
          - name: app10
            namespace: argocd
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: aprojectlol
      source:
        repoURL: https://github.com/ashinsabu3/argocd-example-apps
        targetRevision: HEAD
        path: helm-guestbook
        helm:
          values: |
            replicaCount: 0
            image.tag: 3123
            cm.enable: false
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
