apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{.name}}-guestbook'
      labels: 
        harness.io/serviceRef: svc1
        harness.io/envRef: env1
    spec:
      project: 09c668ce
      source:
        repoURL: https://github.com/ashinsabu3/argocd-example-apps.git
        targetRevision: HEAD
        path: guestbook
      syncPolicy:
        automated: {}
        syncOptions:
         - Validate=true     
         - CreateNamespace=true
         - PruneLast=false
         - ApplyOutOfSyncOnly=false
         - FluxSubsystem=false
         - AutoCreateFluxResources=false
         - Replace=false
         - retry=false
      destination:
        server: '{{.server}}'
        namespace: 'ashin-test3'
