apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example-applicationset
spec:
  generators:
    - list:
        elements:
          - name: app1
            namespace: app1-ns
          - name: app2
            namespace: app2-ns
          - name: app3
            namespace: app3-ns
          - name: app4
            namespace: app4-ns
          - name: app5
            namespace: app5-ns
          - name: app6
            namespace: app6-ns
          - name: app7
            namespace: app7-ns
          - name: app8
            namespace: app8-ns
          - name: app9
            namespace: app9-ns
          - name: app10
            namespace: app10-ns
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: aprojectlol
      source:
        repoURL: https://github.com/example-org/example-apps.git
        targetRevision: HEAD
        path: helm-guestbook
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
