apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - clusters: 
      values:
        svc: test2
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
      values:
        svc: test
  template:
    metadata:
      name: '{{.name}}-guestbook'
      labels: 
        harness.io/serviceRef: '{{.values.svc}}'
        harness.io/envRef: env1
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/ashinsabu3/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-guestbook
        helm:
          parameters:
          - replicaCount: 0
      syncPolicy:
        automated: {}
        syncOptions:
         - Validate=true     
         - CreateNamespace=true
         - PruneLast=false
         - ApplyOutOfSyncOnly=false
         - FluxSubsystem=false
         - AutoCreateFluxResources=false
         - Replace=false
         - retry=false
      destination:
        server: '{{.server}}'
        namespace: 'ashin-test3'
