image:
  tag: "v2"
  repository: "ibmcom/guestbook"
  pullPolicy: "IfNotPresent"
ingress:
  path: "/"
  hosts:
  - "chart-example.local"
  annotations: {}
  tls: []
  enabled: false
replicaCount: 0
tolerations: []
service:
  port: 80
  type: "ClusterIP"
containerPort: 80
resources:
  limits:
    cpu: "0.2"
    memory: "128Mi"
  requests:
    cpu: "0.2"
    memory: "128Mi"
nodeSelector: {}
affinity: {}
