image:
  tag: "2"
  repository: "ashinsabu/loggerimagerandom"
  pullPolicy: "Always"
ingress:
  path: "/"
  hosts:
  - "abx"
  annotations: {}
  tls: []
  enabled: true
replicaCount: 1
tolerations: []
service:
  port: 80
  type: "ClusterIP"
containerPort: 80
resources:
  limits:
    cpu: "0.3"
    memory: "128Mi"
  requests:
    cpu: "0.2"
    memory: "128Mi"
nodeSelector: {}
affinity: {}
cm:
  enable: true
xyz: <+secrets.getValue("account.avaultsecret")>
