apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        name: {{ .Values.x }}
        name2: {{ .Values.ashinsabu }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              app: guestbook-ui
          matchLabelKeys:
            - pod-template-hash
          nodeAffinityPolicy: Honor
          nodeTaintsPolicy: Ignore
      containers:
      - image: "ashinsabu/loggerimagerandom"
        name: guestbook-ui
        ports:
        - containerPort: 80
        resources:
          limits:
           cpu: 100m
           memory: 100Mi
          requests:
           cpu: 100m
           memory: 100Mi
