apiVersion: v1
kind: Secret
metadata:
  metadata:
  name: {{ template "helm-guestbook.fullname" . }}
  labels:
    app: {{ template "helm-guestbook.name" . }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  secretfordb: {{ .Values.expressionsecret }}
  username1: <+secrets.getValue("account.gitopsagenttok")> 
  othersecret: {{ .Values.hsmsecret }}
