apiVersion: v1
kind: Secret
metadata:
  name: secretexpressions
stringData:
  secretfordb: {{ .Values.expressionsecret }}
  username1: <+secrets.getValue("account.gitopsagenttok")> 
  othersecret: {{ .Values.hsmsecret }}
