apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook22332
  namespace: ashin-to-gitops-private
spec:
  project: 08c6293c
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: helm-guestbook
    helm:
      values: |
        ingress:
          enabled: true
          path: /
          hosts:
            - mydomain.example.com
          annotations:
            kubernetes.io/ingress.class: nginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginxnginx
            kubernetes.io/tls-acme: "true"
          labels: {}
          tls:
            - secretName: mydomain-tls
              hosts:
                - mydomain.example.com destination:
  destination:              
    server: https://kubernetes.default.svc
    namespace: ashin-test2
