apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: guestbook-965
    namespace: argocd
spec:
    project: aprojectlol
    source:
        repoURL: https://github.com/ashinsabu3/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-guestbook
        helm:
            values: |-
                replicaCount: 0
                image:
                  tag: 3
    destination:
        server: https://kubernetes.default.svc
        namespace: ashin-test
    syncPolicy:
        automated:
          enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: guestbook-966
    namespace: argocd
spec:
    project: aprojectlol
    source:
        repoURL: https://github.com/ashinsabu3/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-guestbook
        helm:
            values: |-
                replicaCount: 0
                image:
                  tag: 3
    destination:
        server: https://kubernetes.default.svc
        namespace: ashin-test
    syncPolicy:
        automated:
          enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: guestbook-967
    namespace: argocd
spec:
    project: aprojectlol
    source:
        repoURL: https://github.com/ashinsabu3/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-guestbook
        helm:
            values: |-
                replicaCount: 0
                image:
                  tag: 3
    destination:
        server: https://kubernetes.default.svc
        namespace: ashin-test
    syncPolicy:
        automated:
          enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: guestbook-968
    namespace: argocd
spec:
    project: aprojectlol
    source:
        repoURL: https://github.com/ashinsabu3/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-guestbook
        helm:
            values: |-
                replicaCount: 0
                image:
                  tag: 3
    destination:
        server: https://kubernetes.default.svc
        namespace: ashin-test
    syncPolicy:
        automated:
          enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: guestbook-969
    namespace: argocd
spec:
    project: aprojectlol
    source:
        repoURL: https://github.com/ashinsabu3/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-guestbook
        helm:
            values: |-
                replicaCount: 0
                image:
                  tag: 3
    destination:
        server: https://kubernetes.default.svc
        namespace: ashin-test
    syncPolicy:
        automated:
          enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: guestbook-970
    namespace: argocd
spec:
    project: aprojectlol
    source:
        repoURL: https://github.com/ashinsabu3/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-guestbook
        helm:
            values: |-
                replicaCount: 0
                image:
                  tag: 3
    destination:
        server: https://kubernetes.default.svc
        namespace: ashin-test
    syncPolicy:
        automated:
          enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: guestbook-971
    namespace: argocd
spec:
    project: aprojectlol
    source:
        repoURL: https://github.com/ashinsabu3/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-guestbook
        helm:
            values: |-
                replicaCount: 0
                image:
                  tag: 3
    destination:
        server: https://kubernetes.default.svc
        namespace: ashin-test
    syncPolicy:
        automated:
          enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: guestbook-972
    namespace: argocd
spec:
    project: aprojectlol
    source:
        repoURL: https://github.com/ashinsabu3/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-guestbook
        helm:
            values: |-
                replicaCount: 0
                image:
                  tag: 3
    destination:
        server: https://kubernetes.default.svc
        namespace: ashin-test
    syncPolicy:
        automated:
          enabled: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: guestbook-973
    namespace: argocd
spec:
    project: aprojectlol
    source:
        repoURL: https://github.com/ashinsabu3/argocd-example-apps.git
        targetRevision: HEAD
        path: helm-guestbook
        helm:
            values: |-
                replicaCount: 0
                image:
                  tag: 3
    destination:
        server: https://kubernetes.default.svc
        namespace: ashin-test
    syncPolicy:
        automated:
          enabled: true
