apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "secrets-buster.fullname" . }}
  labels:
    app: {{ template "secrets-buster.name" . }}
    chart: {{ template "secrets-buster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ template "secrets-buster.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "secrets-buster.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          
          envFrom:
          - configMapRef:
              name: {{ .Values.expressionsResolvedConfigmapName }}
          - secretRef:
              name: {{ .Values.expressionsSecretName }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "secrets-buster.fullname" . }}
  labels:
    app: {{ template "secrets-buster.name" . }}
    chart: {{ template "secrets-buster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      name: http
  selector:
    app: {{ template "secrets-buster.name" . }}
    release: {{ .Release.Name }}
